import { Component } from './component';

/**
 * Iterates over an array of components and returns their HTML representation joined together.
 *
 * @param {Array<Component>} components - The array of components to iterate over.
 * @return {string} The joined HTML representation of the components.
 */
export function forEachComponent(components) {
    return components.map((component) => component.getHtml()).join('');
}

/**
 * Generate a function comment for the given function body.
 *
 * @param {Component} component - The component constructor.
 * @param {boolean} condition - The condition to check.
 * @return {string} The HTML generated by the component or an empty string.
 */
export function ifComponent(component, condition) {
    return condition ? component.getHtml() : '';
}
